import tkinter as tk
from tkinter import ttk
from .theme import PALETTE as P


def build_layout(app):
    frame = ttk.Frame(app.root, style='Root.TFrame', padding=18)
    frame.pack(fill='both', expand=True)
    frame.rowconfigure(0, weight=1)
    frame.columnconfigure(0, weight=1)
    panes = ttk.PanedWindow(frame, orient='horizontal')
    panes.grid(row=0, column=0, sticky='nsew')
    app.panes = panes
    left = ttk.Frame(panes, padding=20, width=450)
    right = ttk.Frame(panes, padding=20, width=560)
    panes.add(left, weight=4)
    panes.add(right, weight=6)
    for panel in (left,right):
        panel.columnconfigure(0, weight=1)
    left.rowconfigure(5, weight=1)
    right.rowconfigure(2, weight=1)
    ttk.Label(left,text='DESCARGAR',style='Title.TLabel').grid(row=0,column=0,sticky='w',pady=(0,16))
    session = ttk.Frame(left)
    session.grid(row=1,column=0,sticky='ew',pady=(0,10))
    app.session_label = ttk.Label(session,textvariable=app.session,style='Muted.TLabel')
    app.session_label.pack(side='left')
    app.login_button = ttk.Button(session,text='Iniciar sesión',command=app.login)
    app.login_button.pack(side='right')
    app.login_actions = ttk.Frame(left)
    app.login_actions.grid(row=2,column=0,sticky='ew',pady=(0,10))
    app.confirm_button = ttk.Button(app.login_actions,text='Ya inicié sesión',command=app.confirm_login)
    app.confirm_button.pack(side='left')
    app.cancel_button = ttk.Button(app.login_actions,text='Cancelar',command=app.cancel_login)
    app.cancel_button.pack(side='left',padx=6)
    app.login_actions.grid_remove()
    course_heading = ttk.Frame(left)
    course_heading.grid(row=3,column=0,sticky='ew')
    ttk.Label(course_heading,text='Curso',style='Muted.TLabel').pack(side='left')
    app.filter_combo = ttk.Combobox(course_heading,textvariable=app.course_filter,
                                    values=('Destacados','Todos'),state='readonly',width=12)
    app.filter_combo.pack(side='right')
    app.filter_combo.bind('<<ComboboxSelected>>',app.filter_courses)
    ttk.Label(course_heading,text='Mostrar:',style='Muted.TLabel').pack(side='right',padx=8)
    app.course_combo = ttk.Combobox(left,state='disabled',width=28)
    app.course_combo.grid(row=4,column=0,sticky='ew',pady=(6,14))
    app.course_combo.bind('<<ComboboxSelected>>',app.course_changed)
    box = ttk.Frame(left)
    box.grid(row=5,column=0,sticky='nsew')
    ttk.Label(box,text='Semanas / secciones',style='Muted.TLabel').pack(anchor='w',pady=(0,6))
    area = ttk.Frame(box)
    area.pack(fill='both',expand=True)
    app.canvas = tk.Canvas(area,height=200,bg=P['panel'],highlightthickness=1,highlightbackground=P['border'])
    scroll = ttk.Scrollbar(area,orient='vertical',command=app.canvas.yview)
    app.canvas.configure(yscrollcommand=scroll.set)
    app.canvas.pack(side='left',fill='both',expand=True)
    scroll.pack(side='right',fill='y')
    app.section_frame = ttk.Frame(app.canvas,padding=8)
    window = app.canvas.create_window(0,0,anchor='nw',window=app.section_frame)
    app.section_frame.bind('<Configure>',lambda e: app.canvas.configure(scrollregion=app.canvas.bbox('all')))
    def resize(event):
        app.canvas.itemconfigure(window,width=event.width)
        app.style.configure('Section.TCheckbutton',wraplength=max(160,event.width-50))
    app.canvas.bind('<Configure>',resize)
    app.canvas.bind('<MouseWheel>',lambda e: app.canvas.yview_scroll(-int(e.delta/120),'units'))
    actions = ttk.Frame(left)
    actions.grid(row=6,column=0,sticky='ew',pady=10)
    app.all_button = ttk.Button(actions,text='Todas disponibles',command=lambda: app.select_all(True))
    app.all_button.pack(side='left')
    app.none_button = ttk.Button(actions,text='Ninguna',command=lambda: app.select_all(False))
    app.none_button.pack(side='left',padx=6)
    app.download_button = ttk.Button(left,text='Descargar selección',style='Accent.TButton',command=app.download)
    app.download_button.grid(row=7,column=0,sticky='ew',pady=(0,16))
    progress = ttk.Frame(left, padding=(0,4))
    progress.grid(row=8,column=0,sticky='ew')
    progress.columnconfigure(0,weight=1)
    app.status_label = ttk.Label(progress,textvariable=app.status,style='Muted.TLabel',wraplength=390)
    app.status_label.grid(row=0,column=0,sticky='ew',pady=(0,8))
    app.bar = ttk.Progressbar(progress,mode='indeterminate')
    app.bar.grid(row=1,column=0,sticky='ew')
    left.bind('<Configure>',lambda e: app.status_label.configure(wraplength=max(180,e.width-40)))

    heading = ttk.Frame(right)
    heading.grid(row=0,column=0,sticky='ew',pady=(0,8))
    ttk.Label(heading,text='BIBLIOTECA LOCAL',style='Title.TLabel').pack(side='left')
    ttk.Button(heading,text='Actualizar',command=app.refresh_tree).pack(side='right')
    app.library_hint = ttk.Label(right,text='',style='Muted.TLabel',wraplength=480)
    app.library_hint.grid(row=1,column=0,sticky='ew',pady=(0,10))
    right.bind('<Configure>',lambda e: app.library_hint.configure(wraplength=max(180,e.width-40)))
    tree_frame = ttk.Frame(right)
    tree_frame.grid(row=2,column=0,sticky='nsew')
    tree_frame.rowconfigure(0,weight=1)
    tree_frame.columnconfigure(0,weight=1)
    app.tree = ttk.Treeview(tree_frame,show='tree',selectmode='browse')
    app.tree.grid(row=0,column=0,sticky='nsew')
    app.tree.column('#0',width=540,minwidth=350,stretch=True)
    sy = ttk.Scrollbar(tree_frame,orient='vertical',command=app.tree.yview)
    sx = ttk.Scrollbar(tree_frame,orient='horizontal',command=app.tree.xview)
    sy.grid(row=0,column=1,sticky='ns')
    sx.grid(row=1,column=0,sticky='ew')
    app.tree.configure(yscrollcommand=sy.set,xscrollcommand=sx.set)
    app.tree.bind('<Double-1>',app.open_file)
    app.tree.bind('<<TreeviewSelect>>',lambda e: app.update_library_actions())
    for event in ('<<TreeviewOpen>>', '<<TreeviewClose>>'):
        app.tree.bind(event,lambda e: app.root.after_idle(app.update_library_hint))
    app.tree.bind('<Button-3>',app.context_menu)
    buttons = ttk.Frame(right)
    buttons.grid(row=3,column=0,sticky='ew',pady=(12,0))
    app.open_button = ttk.Button(buttons,text='Abrir archivo',command=app.open_selected)
    app.open_button.pack(side='left')
    app.location_button = ttk.Button(buttons,text='Abrir ubicación',command=app.open_location)
    app.location_button.pack(side='left',padx=6)
    app.zip_button = ttk.Button(buttons,text='Exportar ZIP',command=app.zip_selected)
    app.zip_button.pack(side='left')
    app.menu = tk.Menu(app.root,tearoff=False,bg=P['panel'],fg=P['text'],activebackground=P['deep'],activeforeground=P['text'])

    app.details_button = ttk.Button(frame,text='▸ Ver detalles',command=app.toggle_details)
    app.details_button.grid(row=1,column=0,sticky='w',pady=(10,0))
    app.details_frame = ttk.Frame(frame)
    app.details_frame.grid(row=2,column=0,sticky='ew',pady=(8,0))
    app.log = tk.Text(app.details_frame,height=5,state='disabled',wrap='word',bg=P['panel'],fg=P['muted'],insertbackground=P['text'],relief='flat',font=('Consolas',9),padx=10,pady=8)
    app.log.pack(side='left',fill='both',expand=True)
    app.log.configure(state='normal')
    app.log.insert('1.0','Todavía no hay operaciones registradas.')
    app.log.configure(state='disabled')
    log_scroll = ttk.Scrollbar(app.details_frame,command=app.log.yview)
    log_scroll.pack(side='right',fill='y')
    app.log.configure(yscrollcommand=log_scroll.set)
    app.details_frame.grid_remove()
    app.update_controls()
